export const CAMPSITES_LOADING = 'CAMPSITES_LOADING';
export const CAMPSITES_FAILED = 'CAMPSITES_FAILED';
export const ADD_CAMPSITES = 'ADD_CAMPSITES';


export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';


export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';
// this is new //
export const ADD_PARTNERS = 'ADD_PARTNRS';
export const PARTNERS_LOADING='PARTNERS_LOADING';
export const PARTNERS_FAILED = 'PARTNERS_FAILED';